version: 'MedLaunch-{branch}.{build}'
branches:
  only:
  - dev
  - master

configuration: Release
shallow_clone: true
environment:
  FTP_USER: 
    secure: uuO55CqCVyoMZ2NMlf30Qg==
  FTP_PASS: 
    secure: q4KkytZUmTNrJN+dGMwnqA==
before_build:
- cmd: >-
    powershell.exe ".\BuildTools\AppveyorVersioning.ps1"

    nuget restore MedLaunch.sln
build:
  project: MedLaunch/MedLaunch.csproj
  verbosity: minimal
before_package:
- cmd: >-
    powershell.exe ".\BuildTools\AppveyorPackaging.ps1"

test: off
artifacts:
- path: MedLaunch\bin\Release\
  name: '$(ML_ARTIFACT_NAME)'

