version: 'MedLaunch-{branch}.{build}'
branches:
  only:
  - dev
  - master

configuration: Release
shallow_clone: false
environment:
  FTP_USER: 
    secure: uuO55CqCVyoMZ2NMlf30Qg==
  FTP_PASS: 
    secure: q4KkytZUmTNrJN+dGMwnqA==
before_build:
- cmd: >-
    powershell.exe ".\BuildTools\AppveyorVersioning.ps1"

    nuget restore MedLaunch.sln
build:
  project: MedLaunch/MedLaunch.csproj
  verbosity: quiet
before_package:
- cmd: >-
    powershell.exe ".\BuildTools\AppveyorPackaging.ps1"

test: off
artifacts:
- path: MedLaunch\bin\Release\
  name: '$(ML_ARTIFACT_NAME)'
deploy:
- provider: GitHub
  tag: $(MEDLAUNCH_VERSION_DOT)
  release: MedLaunch v$(MEDLAUNCH_VERSION_DOT)
  description: $(MEDLAUNCH_RELEASE_DESCRIPTION)
  auth_token:
    secure: lCQYDdMEEZZKFO0qJkHddSQVHGqB8K1czFJvbBdhfV8X7F17ImQKHvKn7T4S4HM5
  artifact: '$(ML_ARTIFACT_NAME)'
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
after_deploy:
- cmd: powershell.exe ".\BuildTools\AppveyorDeploy.ps1"