using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MedLaunch.Classes.Controls.VirtualDevices
{
    public class Pcfx : VirtualDeviceBase
    {
        public static DeviceDefinition GamePad(int VirtualPort)
        {
            DeviceDefinition device = new DeviceDefinition();
            device.DeviceName = "PCFX GamePad";
            device.ControllerName = "gamepad";
            device.CommandStart = "pcfx.input.port" + VirtualPort;
            device.VirtualPort = VirtualPort;
            device.MapList = new List<Mapping>
            {
                /* MapList is now autogenerated from mednafen.cfg */
            };

            device.CustomOptions = new List<NonControlMapping>
            {
                new NonControlMapping { Description = "Default position for 'MODE 1' switch",
                    MednafenCommand = device.CommandStart + ".gamepad.mode1.defpos",
                    MinValue = 1, MaxValue = 2,
                    ContType = ContrType.COMBO,
                 ConvType = ConvertionType.STRING,
                Values = new List<string>
                {
                    "a",
                    "b"
                }},

                new NonControlMapping { Description = "Default position for 'MODE 2' switch",
                    MednafenCommand = device.CommandStart + ".gamepad.mode2.defpos",
                    MinValue = 1, MaxValue = 2,
                    ContType = ContrType.COMBO,
                 ConvType = ConvertionType.STRING,
                Values = new List<string>
                {
                    "a",
                    "b"
                } },
            };

            DeviceDefinition.ParseOptionsFromConfig(device);
            DeviceDefinition.PopulateConfig(device);
            return device;
        }

        public static DeviceDefinition Mouse(int VirtualPort)
        {
            DeviceDefinition device = new DeviceDefinition();
            device.DeviceName = "PCFX Mouse";
            device.ControllerName = "mouse";
            device.CommandStart = "pcfx.input.port" + VirtualPort;
            device.VirtualPort = VirtualPort;
            device.MapList = new List<Mapping>
            {
                /* MapList is now autogenerated from mednafen.cfg */
            };
            DeviceDefinition.ParseOptionsFromConfig(device);
            DeviceDefinition.PopulateConfig(device);
            return device;
        }
    }
}
